### ISSUE TITLE
io_replay & io_replay_clear

### ISSUE THREAD

**Issue by polluks** [tschak909/platoterm-x11#2]
````
cc -g -L/usr/X11/lib -o platoterm main.o touch.o io.o keyboard.o screen.o terminal.o protocol.o -lX11 
Undefined symbols:
  "_io_replay", referenced from:
      _screen_main in screen.o
  "_io_replay_clear", referenced from:
      _screen_clear in screen.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *** [platoterm] Error 1
````

**Comment by tschak909** [comment]
This should be fixed now with my latest sync from my sparc.

**Comment by polluks** [comment]
![OS X](https://user-images.githubusercontent.com/4707573/123474362-238e4a00-d5fa-11eb-8333-cc066e0cb34c.png)
Now it works on Mac :-)

**Comment by tschak909** [comment]
@polluks  I'm hoping this will be a good basis for most vintage X workstations, as a great many of these machines can't really participate in the modern internet, as such.
